maintainer:
    name: Aaron Halfaker
    email: aaron.halfaker@gmail.com

root_dir: /diffengine

daemons:
    defaults: {}
    
    simplewiki (dev):
        class: diffengine.daemons.Syncronizer
        synchronizers:
            - simplewiki_local
        logging: development
    
    enwiki:
        class: diffengine.daemons.WebserverAndSynchronizer
        synchronizers:
            - enwiki_local
        web: production
        logging: production

synchronizers:
    defaults: {}
    
    simplewiki:
        class: diffengine.synchronizers.Changes
        source: simplewiki_api
        engine: simplewiki_local
    
    enwiki:
        class: diffengine.synchronizers.Changes
        source: enwiki_api
        engine: enwiki_local


webservers:
    defaults:
        class: diffengine.webservers.DiffAPI
        port: 80
    
    simplewiki_diffapi_dev:
        engines: simplewiki_local
        domain: diffengine.localhost.org
        root: /
        
    enwiki_diffapi:
        store: enwiki_local
        domain: diffengine.wmflabs.org
        root: /

engines:
    defaults: {}
    
    simplewiki_local:
        class: diffengine.engines.SegmentMatcher
        wiki: simplewiki
        store: simplewiki_local
        segmenter: western_psw
        tokenizer: wikitext_split
    
    enwiki_local:
        class: diffengine.engines.SegmentMatcher
        wiki: enwiki
        store: enwiki_local
        segmenter: western_psw
        tokenizer: wikitext_split

sources:
    defaults: {}
    
    simplewiki_api:
        class: diffengine.sources.API
        wiki: testwiki
        max_wait: 10
    
    enwiki_api:
        class: diffengine.sources.API
        wiki: enwiki
        max_wait: 5

stores:
    defaults: {}
    
    simplewiki_local:
        class: diffengine.store.Mongo
        host: localhost
        database: simplewiki
    

    enwiki_local:
        class: diffengine.store.Mongo
        host: localhost
        database: enwiki
    

wikis:
    defaults:
        protocol: https
        port: 443
        paths:
            pages: /wiki/
            scripts: /w/
        scripts:
            index: index.php
            api: api.php
    
    enwiki:
        domain: en.wikipedia.org
        
    simplewiki:
        domain: simple.wikipedia.org

tokenizers:
    defaults: {}
    
    wikitext_split:
        class: diffengine.tokenizers.WikitextSplit

segmenters:
    defaults: {}
    
    western_psw:
        class: deltas.segmenters.ParagraphSentencesAndWhitespace
        min_segment: 5
        whitespace: "[\\r\\n\\t\\ ]+"
        paragraph_split: "[\\t\\ \\r]*[\n][\\t\\ \\r]*[\n][\\t\\ \\r]*"
        sentence_end: "[.?!]+"


loggers:
    defaults:
        formatters:
            human:
                format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
                datefmt: '%Y-%m-%d %H:%M:%S'
            json:
                class: jsonlogger.JsonFormatter
        handlers:
            std_err:
                class: logging.handlers.StreamHandler
                formatter: human
                stream  : ext://sys.stdout
            var_log:
                class: logging.handlers.RotatingFileHandler
                formatter: json
                level: ERROR
                filename: /var/log/diffengine/error.json
                maxBytes: 1048576
                backupCount: 5
    
    development:
        loggers:
            main:
                handlers: [std_err]
    production:
        loggers:
            main:
                handlers: [var_log]
              
    
