maintainer:
    name: Aaron Halfaker
    email: aaron.halfaker@gmail.com

root_dir: /diffengine

daemons:
    defaults: {}
    
    simplewiki (dev):
        class: diffengine.daemons.Syncronizer
        synchronizers:
            - simplewiki_local
        logging: development
    
    enwiki:
        class: diffengine.daemons.WebserverAndSynchronizer
        synchronizers:
            - enwiki_local
        web: production
        logging: production


synchronizers:
    defaults: {}
    
    simplewiki_local:
        class: diffengine.synchronizers.Changes
        source: simplewiki_api
        engine: simplewiki_local
    
    enwiki_local:
        class: diffengine.synchronizers.Changes
        source: enwiki_api
        engine: enwiki_local


webservers:
    defaults:
        class: diffengine.webservers.DiffAPI
        port: 80
    
    simplewiki_diffapi_dev:
        stores:
            - enwiki_local
        domain: diffengine.localhost.org
        root: /
        
    enwiki_diffapi:
        store: enwiki_local
        domain: diffengine.wmflabs.org
        root: /

engines:
    defaults: {}
    
    Simple English Wikipedia (local, development):
        class: diffengine.engines.SegmentMatcher
        wiki: simplewiki
        segmenter: western_psw
        tokenizer: wikitext_split
    
    English Wikipedia (local, development):
        class: diffengine.engines.SegmentMatcher
        wiki: enwiki
        segmenter: western_psw
        tokenizer: wikitext_split

sources:
    defaults: {}
    
    simplewiki_api:
        class: diffengine.sources.API
        wiki: testwiki
        max_wait: 10
    
    enwiki_api:
        class: diffengine.sources.API
        wiki: enwiki
        max_wait: 5

stores:
    defaults:
        port: 27017
        w: 1
    
    simplewiki_local:
        class: diffengine.stores.Mongo
        host: localhost
        db_name: simplewiki
    
    enwiki_local:
        class: diffengine.stores.Mongo
        host: localhost
        db_name: enwiki
    

wikis:
    defaults:
        protocol: https
        port: 443
        paths:
            pages: /wiki/
            scripts: /w/
        scripts:
            index: index.php
            api: api.php
    
    enwiki:
        name: English Wikipedia
        domain: en.wikipedia.org
        dbname: enwiki
        
    simplewiki:
        name: Simple English Wikipedia
        domain: simple.wikipedia.org
        dbname: simplewiki

tokenizers:
    defaults: {}
    
    wikitext_split:
        class: diffengine.tokenizers.WikitextSplit

segmenters:
    defaults: {}
    
    western_psw:
        class: diffengine.segmenters.ParagraphsSentencesAndWhitespace
        min_sentence: 5
        whitespace: "[\\r\\n\\t\\ ]+"
        paragraph_split: "[\\t\\ \\r]*[\n][\\t\\ \\r]*[\n][\\t\\ \\r]*"
        sentence_end: "[.?!]+"


loggers:
    defaults:
        version: 1
        formatters:
            human:
                format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
                datefmt: '%Y-%m-%d %H:%M:%S'
            json:
                class: jsonlogger.JsonFormatter
        handlers:
            std_err:
                class: logging.StreamHandler
                formatter: human
                stream  : ext://sys.stderr
            #var_log:
            #    class: logging.handlers.RotatingFileHandler
            #    formatter: json
            #    level: ERROR
            #    filename: /var/log/diffengine/error.json
            #    maxBytes: 1048576
            #    backupCount: 5
    
    debug:
        loggers:
            'diffengine':
                handlers: [std_err]
                level: DEBUG
            'primer':
                handlers: [std_err]
                level: DEBUG
            'daemon':
                handlers: [std_err]
                level: DEBUG

    development:
        loggers:
            'primer':
                handlers: [std_err]
                level: INFO
            'daemon':
                handlers: [std_err]
                level: INFO
    production:
        loggers:
            'primer':
                handlers:
                    - std_err_info
                    - var_log
                level: INFO
            'daemon':
                handlers:
                    - std_err_info
                    - var_log
                level: INFO
